# Generated by Django 5.2.1 on 2025-05-25 19:04

import django.db.models.deletion
import django.utils.timezone
import tours.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', models.TextField(verbose_name='Основной текст о компании')),
            ],
            options={
                'verbose_name': "Контент страницы 'О компании'",
                'verbose_name_plural': "Контент страницы 'О компании'",
            },
        ),
        migrations.CreateModel(
            name='CompanyHistoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('event_description', models.TextField(verbose_name='Описание события')),
            ],
            options={
                'verbose_name': 'Пункт истории компании',
                'verbose_name_plural': 'История компании (по годам)',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='CompanyLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Логотип компании', max_length=100, verbose_name='Название/тип логотипа')),
                ('logo_image', models.ImageField(upload_to='company_logos/', verbose_name='Файл логотипа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Логотип компании',
                'verbose_name_plural': 'Логотипы компании',
            },
        ),
        migrations.CreateModel(
            name='CompanyRequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование реквизита')),
                ('value', models.TextField(verbose_name='Значение реквизита')),
            ],
            options={
                'verbose_name': 'Реквизит компании',
                'verbose_name_plural': 'Реквизиты компании',
            },
        ),
        migrations.CreateModel(
            name='CompanyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название видео')),
                ('video_url', models.URLField(verbose_name='Ссылка на видео')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Видео компании',
                'verbose_name_plural': 'Видео компании',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название страны')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Вопрос-Ответ (FAQ)',
                'verbose_name_plural': 'Вопросы-Ответы (FAQ)',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('discount', models.PositiveSmallIntegerField()),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ['-valid_until'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('short_content', models.TextField(verbose_name='Краткое содержание (одно предложение)')),
                ('full_content', models.TextField(verbose_name='Полное содержание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='article_images/', verbose_name='Изображение')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Статья (Новость)',
                'verbose_name_plural': 'Статьи (Новости)',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=20, validators=[tours.models.validate_phone], verbose_name='Номер телефона')),
                ('birth_date', models.DateField(validators=[tours.models.validate_adult], verbose_name='Дата рождения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль клиента',
                'verbose_name_plural': 'Профили клиентов',
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/', verbose_name='Фото сотрудника')),
                ('work_description', models.TextField(blank=True, verbose_name='Описание выполняемых работ')),
                ('phone_number', models.CharField(max_length=20, validators=[tours.models.validate_phone], verbose_name='Номер телефона')),
                ('birth_date', models.DateField(validators=[tours.models.validate_adult], verbose_name='Дата рождения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь (сотрудник)')),
            ],
            options={
                'verbose_name': 'Профиль сотрудника',
                'verbose_name_plural': 'Профили сотрудников',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название отеля')),
                ('stars', models.PositiveSmallIntegerField(choices=[(1, '1*'), (2, '2*'), (3, '3*'), (4, '4*'), (5, '5*')], verbose_name='Количество звезд')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость за ночь')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='hotel_photos/', verbose_name='Фото отеля')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='tours.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отзыва')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент (автор отзыва)')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название путевки')),
                ('duration_weeks', models.PositiveSmallIntegerField(choices=[(1, '1 неделя'), (2, '2 недели'), (4, '4 недели')], verbose_name='Длительность (недели)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость путевки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_hot_deal', models.BooleanField(default=False, verbose_name='Горящая путевка')),
                ('additional_services', models.TextField(blank=True, verbose_name='Дополнительные услуги')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_packages', to='tours.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Путевка',
                'verbose_name_plural': 'Путевки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('departure_date', models.DateField(verbose_name='Дата отправления')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Общая стоимость')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('confirmed', 'Подтвержден'), ('paid', 'Оплачен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус заказа')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_client', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_as_employee', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник (оформил)')),
                ('tour_packages', models.ManyToManyField(related_name='orders', to='tours.tourpackage', verbose_name='Приобретенные путевки')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='SeasonClimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('winter', 'Зима'), ('spring', 'Весна'), ('summer', 'Лето'), ('autumn', 'Осень')], max_length=10, verbose_name='Сезон')),
                ('climate_description', models.TextField(verbose_name='Описание климата')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climates', to='tours.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Климат по сезонам',
                'verbose_name_plural': 'Климаты по сезонам',
                'unique_together': {('country', 'season')},
            },
        ),
    ]
