from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

urlpatterns = [
    path('tours/', views.tours_catalog, name='tours-catalog'),
    path('sales-chart/', views.sales_distribution_chart, name='sales-chart'),
    path('weather/', views.weather_page, name='weather_external'),
    path('currency/', views.currency_page, name='currency_external'),
    path('catalog/', views.tours_catalog, name='tours_catalog'),
    path('dashboard/', views.user_dashboard, name='user_dashboard'),
    path('client/', views.client_dashboard, name='client_dashboard'),
    path('employee/', views.employee_dashboard, name='employee_dashboard'),
    path('clients-tours/', views.admin_clients_with_tours, name='admin_clients_with_tours'),
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('news/', views.news_list, name='news-list'),
    path('faq/', views.faq_list, name='faq-list'),
    path('contacts/', views.contacts, name='contacts'),
    path('privacy/', views.privacy_policy, name='privacy-policy'),
    path('vacancies/', views.vacancy_list, name='vacancy-list'),
    path('reviews/', views.review_list, name='review-list'),
    path('promocodes/', views.promocode_list, name='promocode-list'),
    path('countries/', views.CountryListView.as_view(), name='country-list'),
    path('countries/create/', views.CountryCreateView.as_view(), name='country-create'),
    path('countries/<int:pk>/', views.CountryDetailView.as_view(), name='country-detail'),
    path('countries/<int:pk>/update/', views.CountryUpdateView.as_view(), name='country-update'),
    path('countries/<int:pk>/delete/', views.CountryDeleteView.as_view(), name='country-delete'),
    path('clients/', views.ClientProfileListView.as_view(), name='client-list'),
    path('clients/create/', views.ClientProfileCreateView.as_view(), name='client-create'),
    path('clients/<int:pk>/', views.ClientProfileDetailView.as_view(), name='client-detail'),
    path('clients/<int:pk>/update/', views.ClientProfileUpdateView.as_view(), name='client-update'),
    path('clients/<int:pk>/delete/', views.ClientProfileDeleteView.as_view(), name='client-delete'),
    path('employees/', views.EmployeeProfileListView.as_view(), name='employee-list'),
    path('employees/create/', views.EmployeeProfileCreateView.as_view(), name='employee-create'),
    path('employees/<int:pk>/', views.EmployeeProfileDetailView.as_view(), name='employee-detail'),
    path('employees/<int:pk>/update/', views.EmployeeProfileUpdateView.as_view(), name='employee-update'),
    path('employees/<int:pk>/delete/', views.EmployeeProfileDeleteView.as_view(), name='employee-delete'),
    path('climates/', views.SeasonClimateListView.as_view(), name='seasonclimate-list'),
    path('climates/create/', views.SeasonClimateCreateView.as_view(), name='seasonclimate-create'),
    path('climates/<int:pk>/', views.SeasonClimateDetailView.as_view(), name='seasonclimate-detail'),
    path('climates/<int:pk>/update/', views.SeasonClimateUpdateView.as_view(), name='seasonclimate-update'),
    path('climates/<int:pk>/delete/', views.SeasonClimateDeleteView.as_view(), name='seasonclimate-delete'),
    path('hotels/', views.HotelListView.as_view(), name='hotel-list'),
    path('hotels/create/', views.HotelCreateView.as_view(), name='hotel-create'),
    path('hotels/<int:pk>/', views.HotelDetailView.as_view(), name='hotel-detail'),
    path('hotels/<int:pk>/update/', views.HotelUpdateView.as_view(), name='hotel-update'),
    path('hotels/<int:pk>/delete/', views.HotelDeleteView.as_view(), name='hotel-delete'),
    path('tour-packages/', views.TourPackageListView.as_view(), name='tourpackage-list'),
    path('tour-packages/create/', views.TourPackageCreateView.as_view(), name='tourpackage-create'),
    path('tour-packages/<int:pk>/', views.TourPackageDetailView.as_view(), name='tourpackage-detail'),
    path('tour-packages/<int:pk>/update/', views.TourPackageUpdateView.as_view(), name='tourpackage-update'),
    path('tour-packages/<int:pk>/delete/', views.TourPackageDeleteView.as_view(), name='tourpackage-delete'),
    path('orders/', views.OrderListView.as_view(), name='order-list'),
    path('orders/create/', views.OrderCreateView.as_view(), name='order-create'),
    path('orders/<int:pk>/', views.OrderDetailView.as_view(), name='order-detail'),
    path('orders/<int:pk>/update/', views.OrderUpdateView.as_view(), name='order-update'),
    path('orders/<int:pk>/delete/', views.OrderDeleteView.as_view(), name='order-delete'),
    path('articles/', views.ArticleListView.as_view(), name='article-list'),
    path('articles/create/', views.ArticleCreateView.as_view(), name='article-create'),
    path('articles/<int:pk>/', views.ArticleDetailView.as_view(), name='article-detail'),
    path('articles/<int:pk>/update/', views.ArticleUpdateView.as_view(), name='article-update'),
    path('articles/<int:pk>/delete/', views.ArticleDeleteView.as_view(), name='article-delete'),
    path('faqs/', views.FAQListView.as_view(), name='faq-list'),
    path('faqs/create/', views.FAQCreateView.as_view(), name='faq-create'),
    path('faqs/<int:pk>/', views.FAQDetailView.as_view(), name='faq-detail'),
    path('faqs/<int:pk>/update/', views.FAQUpdateView.as_view(), name='faq-update'),
    path('faqs/<int:pk>/delete/', views.FAQDeleteView.as_view(), name='faq-delete'),
    path('vacancies/', views.VacancyListView.as_view(), name='vacancy-list'),
    path('vacancies/create/', views.VacancyCreateView.as_view(), name='vacancy-create'),
    path('vacancies/<int:pk>/', views.VacancyDetailView.as_view(), name='vacancy-detail'),
    path('vacancies/<int:pk>/update/', views.VacancyUpdateView.as_view(), name='vacancy-update'),
    path('vacancies/<int:pk>/delete/', views.VacancyDeleteView.as_view(), name='vacancy-delete'),
    path('reviews/', views.ReviewListView.as_view(), name='review-list'),
    path('reviews/create/', views.ReviewCreateView.as_view(), name='review-create'),
    path('reviews/<int:pk>/', views.ReviewDetailView.as_view(), name='review-detail'),
    path('reviews/<int:pk>/update/', views.ReviewUpdateView.as_view(), name='review-update'),
    path('reviews/<int:pk>/delete/', views.ReviewDeleteView.as_view(), name='review-delete'),
    path('promocodes/', views.PromoCodeListView.as_view(), name='promocode-list'),
    path('promocodes/create/', views.PromoCodeCreateView.as_view(), name='promocode-create'),
    path('promocodes/<int:pk>/', views.PromoCodeDetailView.as_view(), name='promocode-detail'),
    path('promocodes/<int:pk>/update/', views.PromoCodeUpdateView.as_view(), name='promocode-update'),
    path('promocodes/<int:pk>/delete/', views.PromoCodeDeleteView.as_view(), name='promocode-delete'),
    path('about/', views.AboutPageContentListView.as_view(), name='aboutpagecontent-list'),
    path('about/create/', views.AboutPageContentCreateView.as_view(), name='aboutpagecontent-create'),
    path('about/<int:pk>/', views.AboutPageContentDetailView.as_view(), name='aboutpagecontent-detail'),
    path('about/<int:pk>/update/', views.AboutPageContentUpdateView.as_view(), name='aboutpagecontent-update'),
    path('about/<int:pk>/delete/', views.AboutPageContentDeleteView.as_view(), name='aboutpagecontent-delete'),
    path('company-videos/', views.CompanyVideoListView.as_view(), name='companyvideo-list'),
    path('company-videos/create/', views.CompanyVideoCreateView.as_view(), name='companyvideo-create'),
    path('company-videos/<int:pk>/', views.CompanyVideoDetailView.as_view(), name='companyvideo-detail'),
    path('company-videos/<int:pk>/update/', views.CompanyVideoUpdateView.as_view(), name='companyvideo-update'),
    path('company-videos/<int:pk>/delete/', views.CompanyVideoDeleteView.as_view(), name='companyvideo-delete'),
    path('company-logos/', views.CompanyLogoListView.as_view(), name='companylogo-list'),
    path('company-logos/create/', views.CompanyLogoCreateView.as_view(), name='companylogo-create'),
    path('company-logos/<int:pk>/', views.CompanyLogoDetailView.as_view(), name='companylogo-detail'),
    path('company-logos/<int:pk>/update/', views.CompanyLogoUpdateView.as_view(), name='companylogo-update'),
    path('company-logos/<int:pk>/delete/', views.CompanyLogoDeleteView.as_view(), name='companylogo-delete'),
    path('company-history/', views.CompanyHistoryItemListView.as_view(), name='companyhistoryitem-list'),
    path('company-history/create/', views.CompanyHistoryItemCreateView.as_view(), name='companyhistoryitem-create'),
    path('company-history/<int:pk>/', views.CompanyHistoryItemDetailView.as_view(), name='companyhistoryitem-detail'),
    path('company-history/<int:pk>/update/', views.CompanyHistoryItemUpdateView.as_view(),
         name='companyhistoryitem-update'),
    path('company-history/<int:pk>/delete/', views.CompanyHistoryItemDeleteView.as_view(),
         name='companyhistoryitem-delete'),
    path('company-requisites/', views.CompanyRequisiteListView.as_view(), name='companyrequisite-list'),
    path('company-requisites/create/', views.CompanyRequisiteCreateView.as_view(), name='companyrequisite-create'),
    path('company-requisites/<int:pk>/', views.CompanyRequisiteDetailView.as_view(), name='companyrequisite-detail'),
    path('company-requisites/<int:pk>/update/', views.CompanyRequisiteUpdateView.as_view(),
         name='companyrequisite-update'),
    path('company-requisites/<int:pk>/delete/', views.CompanyRequisiteDeleteView.as_view(),
         name='companyrequisite-delete'),

]